/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
/**
 *
 * @author Jose
 */
public class UserManagementForm extends javax.swing.JFrame {

    /**
     * Creates new form UserManagementForm
     */
    AdminForm preForm;
    
    public UserManagementForm() {
        initComponents();
        this.setLayout(null);
    }
    
    public UserManagementForm(AdminForm form) {
        initComponents();
        preForm = form;
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionGroup = new javax.swing.ButtonGroup();
        userGroup = new javax.swing.ButtonGroup();
        messagePane = new javax.swing.JOptionPane();
        addUserButton = new javax.swing.JRadioButton();
        removeUserButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        idBox = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        fNameLabel = new javax.swing.JLabel();
        fNameBox = new javax.swing.JTextField();
        emailLable = new javax.swing.JLabel();
        lNameBox = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        userBtn = new javax.swing.JRadioButton();
        sUserBtn = new javax.swing.JRadioButton();
        patronBtn = new javax.swing.JRadioButton();
        passLabel = new javax.swing.JLabel();
        passBox = new javax.swing.JTextField();
        addUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Management");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        actionGroup.add(addUserButton);
        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        actionGroup.add(removeUserButton);
        removeUserButton.setText("Remove User");
        removeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("User ID:");

        removeBtn.setText("Remove User");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        fNameLabel.setText("First Name:");

        emailLable.setText("Email:");

        lNameLabel.setText("Last Name:");

        userGroup.add(userBtn);
        userBtn.setText("User");
        userBtn.setActionCommand("");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        userGroup.add(sUserBtn);
        sUserBtn.setText("Super User");
        sUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUserBtnActionPerformed(evt);
            }
        });

        userGroup.add(patronBtn);
        patronBtn.setText("Patron");
        patronBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patronBtnActionPerformed(evt);
            }
        });

        passLabel.setText("Password:");

        addUserBtn.setText("Add User");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(passLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userBtn)
                                .addGap(10, 10, 10)
                                .addComponent(sUserBtn)
                                .addGap(10, 10, 10)
                                .addComponent(patronBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addComponent(jLabel1))
                                                .addComponent(fNameLabel))
                                            .addGap(30, 30, 30)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(fNameBox)
                                                .addComponent(idBox)
                                                .addComponent(lNameBox)
                                                .addComponent(emailBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(emailLable)
                                            .addGap(137, 137, 137))
                                        .addComponent(lNameLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addUserButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeUserButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(removeUserButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(removeBtn)
                    .addComponent(fNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userBtn)
                    .addComponent(sUserBtn)
                    .addComponent(patronBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addUserBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserButtonActionPerformed
        this.setSize(230, 165);
        this.setLocationRelativeTo(null);
        fNameBox.setVisible(false);
        fNameLabel.setVisible(false);
        removeBtn.setVisible(true);
        removeBtn.setLocation(60, 100);
    }//GEN-LAST:event_removeUserButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        userGroup.clearSelection();
        removeBtn.setVisible(false);
        fNameBox.setVisible(true);
        fNameLabel.setVisible(true);
        this.setSize(265, 270);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void patronBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patronBtnActionPerformed
        passLabel.setVisible(false);
        passBox.setVisible(false);
        this.setSize(265, 310);
        addUserBtn.setVisible(true);
        addUserBtn.setLocation(80, 250);
    }//GEN-LAST:event_patronBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        this.setSize(265, 350);
        addUserBtn.setVisible(true);
        addUserBtn.setLocation(80, 285);
        passLabel.setVisible(true);
        passBox.setVisible(true);
    }//GEN-LAST:event_userBtnActionPerformed

    private void sUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUserBtnActionPerformed
        this.setSize(265, 350);
        addUserBtn.setVisible(true);
        addUserBtn.setLocation(80, 285);
        passLabel.setVisible(true);
        passBox.setVisible(true);
    }//GEN-LAST:event_sUserBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        preForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        try{
            Socket s = new Socket("localHost", 8765);
             String message = "addPerson";
            
            OutputStream os = s.getOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(message);
            
            InputStream is = s.getInputStream();
            ObjectInputStream ois = new ObjectInputStream(is);
            message = (String)ois.readObject();
            
            if(message.equals("OK")){
                System.out.println(message);
                addPerson(s);
            }else{
                JOptionPane.showMessageDialog(messagePane, "Error");
            }
            ois.close();
            is.close();
            os.close();
            s.close();            
        }catch(Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void addPerson(Socket s){
        try{
            Person u;
            if(sUserBtn.isSelected() == true){
                u = new User(idBox.getText(), fNameBox.getText(), lNameBox.getText(), emailBox.getText(), passBox.getText(), User.UserType.SUPERUSER);
            }else if(userBtn.isSelected() == true){
                 u = new User(idBox.getText(), fNameBox.getText(), lNameBox.getText(), emailBox.getText(), passBox.getText(), User.UserType.USER);
            }else{
                u = new Patron(idBox.getText(), fNameBox.getText(), lNameBox.getText(), emailBox.getText());
            }
            OutputStream os = s.getOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(u);
            
            InputStream is = s.getInputStream();
            ObjectInputStream ois = new ObjectInputStream(is);
            String message = (String)ois.readObject();
            System.out.println(message);
            if(message.equals("1")){
                JOptionPane.showMessageDialog(messagePane, "User Added Succesfully");
            }else{
                JOptionPane.showMessageDialog(messagePane, "User already Exists");
            }
        }catch(Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }
    
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        try{
            Socket s = new Socket("localHost", 8765);
            String message = "deleteUser";
            OutputStream os = s.getOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(message);
            
            InputStream is = s.getInputStream();
            ObjectInputStream ois = new ObjectInputStream(is);
            message = (String)ois.readObject();
            if(message.equals("OK")){
                System.out.println(message);
                removePerson(s);
            }else{
                JOptionPane.showMessageDialog(messagePane, "Error");
            }
            ois.close();
            is.close();
            os.close();
            s.close();            
        }catch(Exception e){
            System.err.println("Error: " + e.getMessage());
            e.printStackTrace(System.err);
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void removePerson(Socket s){
        try{
            String id = idBox.getText();
            OutputStream os = s.getOutputStream();
            ObjectOutputStream oos = new ObjectOutputStream(os);
            oos.writeObject(id);
            
            InputStream is = s.getInputStream();
            ObjectInputStream ois = new ObjectInputStream(is);
            String message = (String)ois.readObject();
            System.out.println(message);
            if(message.equals("1")){
                JOptionPane.showMessageDialog(messagePane, "Person Removed Succesfully");
            }else{
                JOptionPane.showMessageDialog(messagePane, "Person does not Exists");
            }
        }catch(Exception e){
            System.err.println("Error: " + e.getMessage());
        }     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagementForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup actionGroup;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JRadioButton addUserButton;
    private javax.swing.JTextField emailBox;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField fNameBox;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField idBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lNameBox;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JOptionPane messagePane;
    private javax.swing.JTextField passBox;
    private javax.swing.JLabel passLabel;
    private javax.swing.JRadioButton patronBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JRadioButton removeUserButton;
    private javax.swing.JRadioButton sUserBtn;
    private javax.swing.JRadioButton userBtn;
    private javax.swing.ButtonGroup userGroup;
    // End of variables declaration//GEN-END:variables
}
